version: '3.1'

networks:
  minha_rede:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
services:
  postgres-master:
    image: bitnami/postgresql
    environment:
       - POSTGRESQL_REPLICATION_MODE=master
       - POSTGRESQL_REPLICATION_USER=userbackup
       - POSTGRESQL_REPLICATION_PASSWORD=123456
       - POSTGRESQL_USERNAME=postgres
       - POSTGRESQL_PASSWORD=bd123
       - POSTGRESQL_DATABASE=master
    volumes:
      - ./data/master:/var/lib/postgresql/data
    networks:
      minha_rede:
        ipv4_address: 172.20.0.22
    ports:
      - "5440:5432"
  postgres-slave0:
    image: bitnami/postgresql
    environment:     
       - POSTGRESQL_REPLICATION_MODE=slave
       - POSTGRESQL_REPLICATION_USER=userbackup
       - POSTGRESQL_REPLICATION_PASSWORD=123456
       - POSTGRESQL_MASTER_HOST=postgres-master
       - POSTGRESQL_PASSWORD=123456
       - POSTGRESQL_MASTER_PORT_NUMBER=5432
    volumes:
      - ./data/slave:/var/lib/postgresql/data
    networks:
      minha_rede:
        ipv4_address: 172.20.0.23
    ports:
      - "5441:5432"
    depends_on:
      - postgres-master
  postgres-slave1:
    image: bitnami/postgresql
    environment:
       - POSTGRESQL_REPLICATION_MODE=slave
       - POSTGRESQL_REPLICATION_USER=userbackup
       - POSTGRESQL_REPLICATION_PASSWORD=123456
       - POSTGRESQL_MASTER_HOST=postgres-master
       - POSTGRESQL_PASSWORD=123456
       - POSTGRESQL_MASTER_PORT_NUMBER=5432
    volumes:
      - ./data/slave:/var/lib/postgresql/data
    networks:
      minha_rede:
        ipv4_address: 172.20.0.24
    ports:
      - "5442:5432"
    depends_on:
      - postgres-master      
  postgres-slave2:
    image: bitnami/postgresql
    environment:
       - POSTGRESQL_REPLICATION_MODE=slave
       - POSTGRESQL_REPLICATION_USER=userbackup
       - POSTGRESQL_REPLICATION_PASSWORD=123456
       - POSTGRESQL_MASTER_HOST=postgres-master
       - POSTGRESQL_PASSWORD=123456
       - POSTGRESQL_MASTER_PORT_NUMBER=5432
    volumes:
      - ./data/slave:/var/lib/postgresql/data
    networks:
      minha_rede:
        ipv4_address: 172.20.0.25
    ports:
      - "5443:5432"
    depends_on:
      - postgres-master
  postgres-slave3:
    image: bitnami/postgresql
    environment:
       - POSTGRESQL_REPLICATION_MODE=slave
       - POSTGRESQL_REPLICATION_USER=userbackup
       - POSTGRESQL_REPLICATION_PASSWORD=123456
       - POSTGRESQL_MASTER_HOST=postgres-master
       - POSTGRESQL_PASSWORD=123456
       - POSTGRESQL_MASTER_PORT_NUMBER=5432
    volumes:
      - ./data/slave:/var/lib/postgresql/data
    networks:
      minha_rede:
        ipv4_address: 172.20.0.33
    ports:
      - "5444:5432"
    depends_on:
      - postgres-master
  postgres-slave4:
    image: bitnami/postgresql
    environment:
       - POSTGRESQL_REPLICATION_MODE=slave
       - POSTGRESQL_REPLICATION_USER=userbackup
       - POSTGRESQL_REPLICATION_PASSWORD=123456
       - POSTGRESQL_MASTER_HOST=postgres-master
       - POSTGRESQL_PASSWORD=123456
       - POSTGRESQL_MASTER_PORT_NUMBER=5432
    volumes:
      - ./data/slave:/var/lib/postgresql/data
    networks:
      minha_rede:
        ipv4_address: 172.20.0.28
    ports:
      - "5445:5432"
    depends_on:
      - postgres-master 
  postgres-slave5:
    image: bitnami/postgresql
    environment:
       - POSTGRESQL_REPLICATION_MODE=slave
       - POSTGRESQL_REPLICATION_USER=userbackup
       - POSTGRESQL_REPLICATION_PASSWORD=123456
       - POSTGRESQL_MASTER_HOST=postgres-master
       - POSTGRESQL_PASSWORD=123456
       - POSTGRESQL_MASTER_PORT_NUMBER=5432
    volumes:
      - ./data/slave:/var/lib/postgresql/data
    networks:
      minha_rede:
        ipv4_address: 172.20.0.29
    ports:
      - "5446:5432"
    depends_on:
      - postgres-master 
  postgres-slave6:
    image: bitnami/postgresql
    environment:
       - POSTGRESQL_REPLICATION_MODE=slave
       - POSTGRESQL_REPLICATION_USER=userbackup
       - POSTGRESQL_REPLICATION_PASSWORD=123456
       - POSTGRESQL_MASTER_HOST=postgres-master
       - POSTGRESQL_PASSWORD=123456
       - POSTGRESQL_MASTER_PORT_NUMBER=5432
    volumes:
      - ./data/slave:/var/lib/postgresql/data
    networks:
      minha_rede:
        ipv4_address: 172.20.0.30
    ports:
      - "5447:5432"
    depends_on:
      - postgres-master                        
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "80:80"
    networks:
      minha_rede:
        ipv4_address: 172.20.0.26
    volumes:
      - ./data/pgadmin_data:/var/lib/pgadmin1
  haproxy:
    image: haproxy
    volumes:
      - ./data/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - "5450:5432"
      - "3002:8404"
    networks:
      minha_rede:
        ipv4_address: 172.20.0.32
